// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/2/2025, 7:14:01 PM
const configMerger = require("C:/Laravel 11/htdocs/projects/nuxt-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Laravel 11/htdocs/projects/nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/plugins/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-app/composables/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-app/utils/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-app/app.config.{js,ts,mjs}"] } }));

module.exports = config
