// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/20/2024, 5:50:38 PM
const configMerger = require("C:/Laravel 11/htdocs/projects/nuxt-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Laravel 11/htdocs/projects/nuxt-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/plugins/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-project/composables/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-project/utils/**/*.{js,ts,mjs}","C:/Laravel 11/htdocs/projects/nuxt-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Laravel 11/htdocs/projects/nuxt-project/app.config.{js,ts,mjs}"] } }));

module.exports = config
